In [1]:
# Python Learning

In [1]:
import numpy as np

In [4]:
simple_list=101,102,103

In [6]:
simple_list

(101, 102, 103)

In [7]:
np.array(simple_list)

array([101, 102, 103])

In [11]:
simple_list_Of_list=[[1,2,3],[4,5,6],[7,8,9]]

In [12]:
simple_list_Of_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [13]:
np.array(simple_list_Of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.array(2,3)

TypeError: data type not understood

In [15]:
np.array[1,2]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [16]:
np.arange(1,50)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [5]:
np.arange(3,27,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros(4,3)

TypeError: data type not understood

In [20]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [22]:
np.ones(5,6)

TypeError: data type not understood

In [26]:
np.linspace(3,97)

array([ 3.        ,  4.91836735,  6.83673469,  8.75510204, 10.67346939,
       12.59183673, 14.51020408, 16.42857143, 18.34693878, 20.26530612,
       22.18367347, 24.10204082, 26.02040816, 27.93877551, 29.85714286,
       31.7755102 , 33.69387755, 35.6122449 , 37.53061224, 39.44897959,
       41.36734694, 43.28571429, 45.20408163, 47.12244898, 49.04081633,
       50.95918367, 52.87755102, 54.79591837, 56.71428571, 58.63265306,
       60.55102041, 62.46938776, 64.3877551 , 66.30612245, 68.2244898 ,
       70.14285714, 72.06122449, 73.97959184, 75.89795918, 77.81632653,
       79.73469388, 81.65306122, 83.57142857, 85.48979592, 87.40816327,
       89.32653061, 91.24489796, 93.16326531, 95.08163265, 97.        ])

In [6]:
np.linspace(3,28,3)

array([ 3. , 15.5, 28. ])

In [4]:
np.linspace(3,90,3)

array([ 3. , 46.5, 90. ])

In [32]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.eye(5,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [35]:
np.random.rand(2)

array([0.43924558, 0.28067433])

In [39]:
np.random.random(4,5)

TypeError: random_sample() takes at most 1 positional argument (2 given)

In [40]:
np.random.randint(4,60,6)

array([32, 56, 39, 12,  6, 39])

In [7]:
array_test=np.arange(0,20)

In [42]:
array_test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [43]:
array_test.reshape(3,4)

ValueError: cannot reshape array of size 20 into shape (3,4)

In [44]:
array_test.reshape((3,4))

ValueError: cannot reshape array of size 20 into shape (3,4)

In [45]:
array_test.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [46]:
array_test.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [47]:
array_test.max()

19

In [48]:
array_test.argmax()

19

In [49]:
array_test.argmin()

0

In [9]:
array_test.shape

(20,)

In [10]:
array_test.dtype

dtype('int32')

In [13]:
matrix_arra=np.random.rand(3,4)

In [14]:
matrix_arra

array([[0.69327694, 0.25368551, 0.2791418 , 0.21687405],
       [0.60567973, 0.97799863, 0.47331833, 0.70090544],
       [0.90098252, 0.33574329, 0.33273469, 0.96998411]])

In [15]:
matrix_arra.T

array([[0.69327694, 0.60567973, 0.90098252],
       [0.25368551, 0.97799863, 0.33574329],
       [0.2791418 , 0.47331833, 0.33273469],
       [0.21687405, 0.70090544, 0.96998411]])

In [2]:
New_sample_array=np.arange(25,67)

In [3]:
New_sample_array

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
       59, 60, 61, 62, 63, 64, 65, 66])

In [4]:
New_sample_array[15]

40

In [5]:
New_sample_array[1,3,5]:=101

SyntaxError: invalid syntax (<ipython-input-5-04e5bdafd9c5>, line 1)

In [6]:
New_sample_array[1,3,5]=101

IndexError: too many indices for array

In [7]:
New_sample_array[1]:=101

SyntaxError: invalid syntax (<ipython-input-7-29e4baa3d9ab>, line 1)

In [8]:
New_sample_array[1]=101

In [9]:
New_sample_array

array([ 25, 101,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,
        38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
        51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66])

In [10]:
Sub_Set=New_sample_array[5:10]

In [11]:
Sub_Set

array([30, 31, 32, 33, 34])

In [12]:
Sub_Set[:]=501

In [13]:
Sub_Set

array([501, 501, 501, 501, 501])

In [14]:
New_sample_array

array([ 25, 101,  27,  28,  29, 501, 501, 501, 501, 501,  35,  36,  37,
        38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,
        51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,
        64,  65,  66])

In [15]:
Sub_Set.copy

<function ndarray.copy>

In [16]:
Sub_Set.copy()

array([501, 501, 501, 501, 501])

In [17]:
Sub_Set_1=Sub_Set.copy()

In [18]:
Sub_Set_1

array([501, 501, 501, 501, 501])

In [19]:
Matrix_Array=np.array([1,2,3],[4,5,6],[7,8,9])

ValueError: only 2 non-keyword arguments accepted

In [20]:
Matrix_Array=np.array(([1,2,3],[4,5,6],[7,8,9]))

In [21]:
Matrix_Array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
Matrix_Array[2,1]

8

In [23]:
Matrix_Array[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
Matrix_Array[:,2]

array([3, 6, 9])

In [25]:
Matrix_Array[2,:]

array([7, 8, 9])

In [26]:
Matrix_Array[:1,1:]

array([[2, 3]])

In [27]:
Matrix_Array[:1,:]

array([[1, 2, 3]])

In [28]:
Matrix_Array[:1,:1]

array([[1]])

In [29]:
Matrix_Array[1,1]

5

In [30]:
Matrix_Array[1:,:2]

array([[4, 5],
       [7, 8]])

In [31]:
sample_array2=np.array(1,23)

TypeError: data type not understood

In [32]:
sample_array2=np.array[1,23]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [33]:
sample_array2=np.arange(1,23)

In [34]:
sample_array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

In [35]:
sample_array2[sample_array2>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [38]:
sample_array1=np.arange(1,23)

In [39]:
sample_array1+sample_array2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44])

In [40]:
sample_matrix = np.array(([50,200,5,10,160],[170,10,35,50,15],[125,25,100,145,120],[100,105,25,65,80],[250,15,25,30,100]))


In [41]:
sample_matrix

array([[ 50, 200,   5,  10, 160],
       [170,  10,  35,  50,  15],
       [125,  25, 100, 145, 120],
       [100, 105,  25,  65,  80],
       [250,  15,  25,  30, 100]])

In [42]:
sample_matrix[:3,1:]

array([[200,   5,  10, 160],
       [ 10,  35,  50,  15],
       [ 25, 100, 145, 120]])

In [43]:
np.var(sample_array1)

40.25

In [44]:
np.save('array1',sample_array1)

In [45]:
np.load('array1.npy')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22])

In [46]:
np.savez('array1.npz',a=sample_array1,b=sample_matrix)

In [48]:
archv=np.load('array1.npz')

In [49]:
archv[b]

NameError: name 'b' is not defined

In [50]:
archv['b']

array([[ 50, 200,   5,  10, 160],
       [170,  10,  35,  50,  15],
       [125,  25, 100, 145, 120],
       [100, 105,  25,  65,  80],
       [250,  15,  25,  30, 100]])

In [1]:
####LEARNING PANDAS

import numpy as np
import pandas as pd

In [2]:
list=[21,22,23,24]
index=['N','M','O','P']
dict={'N':21,'M':22,'O':23,'P':24}

In [3]:
list

[21, 22, 23, 24]

In [4]:
index

['N', 'M', 'O', 'P']

In [5]:
dict

{'N': 21, 'M': 22, 'O': 23, 'P': 24}

In [6]:
pd.Series(list)

0    21
1    22
2    23
3    24
dtype: int64

In [7]:
pd.Series(index)

0    N
1    M
2    O
3    P
dtype: object

In [8]:
pd.Series(dict)

N    21
M    22
O    23
P    24
dtype: int64

In [9]:
pd.Series(list,index)

N    21
M    22
O    23
P    24
dtype: int64

In [10]:
pd.Series(array)

NameError: name 'array' is not defined

In [19]:
array=np.array([55,56,57,585])

In [20]:
array

array([ 55,  56,  57, 585])

In [17]:
pd.Series(array)

0     55
1     56
2     57
3    585
4     88
dtype: int32

In [21]:
pd.Series(array,index)

N     55
M     56
O     57
P    585
dtype: int32

In [25]:
Series_1=pd.Series([23,34,45,56,67],index=['K','o','l','m','n'])

In [26]:
Series_1

K    23
o    34
l    45
m    56
n    67
dtype: int64

In [27]:
Series_1['K']

23

In [30]:
Series_2=pd.Series([23,34,45,51,61],index=['K','O','W','m','n'])

In [31]:
Series_1+Series_2

K     46.0
O      NaN
W      NaN
l      NaN
m    107.0
n    128.0
o      NaN
dtype: float64

In [47]:
from numpy.random import randn
np.random.seed(100)

In [34]:
Data_Frame=pd.DataFrame(randn(2,3),index='A B'.split(),columns='Score1 Score2'.split())

ValueError: Shape of passed values is (3, 2), indices imply (2, 2)

In [88]:
Data_Frame=pd.DataFrame(randn(2,3),index='A B'.split(),columns='Score1 Score2 Score3'.split())

In [57]:
Data_Frame

Score1    Score2    Score3
A  0.221180 -1.070043 -0.189496
B  0.255001 -0.458027  0.435163

In [60]:
Data_Frame[['Score3','Score2']]

Score3    Score2
A -0.189496 -1.070043
B  0.435163 -0.458027

In [61]:
Data_Frame['Score4']=Data_Frame['Score3']*Data_Frame['Score2']

In [62]:
Data_Frame

Score1    Score2    Score3    Score4
A  0.221180 -1.070043 -0.189496  0.202769
B  0.255001 -0.458027  0.435163 -0.199317

In [63]:
Data_Frame.drop['Score4']

TypeError: 'method' object is not subscriptable

In [64]:
Data_Frame.drop('Score4')

KeyError: "labels ['Score4'] not contained in axis"

In [65]:
Data_Frame.drop('Score4',axis=0)

KeyError: "labels ['Score4'] not contained in axis"

In [66]:
Data_Frame.drop('Score4',axis=1)

Score1    Score2    Score3
A  0.221180 -1.070043 -0.189496
B  0.255001 -0.458027  0.435163

In [67]:
Data_Frame

Score1    Score2    Score3    Score4
A  0.221180 -1.070043 -0.189496  0.202769
B  0.255001 -0.458027  0.435163 -0.199317

In [68]:
Data_Frame.drop('Score4',axis=1,inplace=TRUE)

NameError: name 'TRUE' is not defined

In [69]:
Data_Frame.drop('Score4',axis=1,inplace='TRUE')

ValueError: For argument "inplace" expected type bool, received type str.

In [70]:
Data_Frame.drop('Score4',axis=1,inplace=True)

In [71]:
Data_Frame

Score1    Score2    Score3
A  0.221180 -1.070043 -0.189496
B  0.255001 -0.458027  0.435163

In [72]:
Data_Frame.drop('Score',axis=1,inplace=True)

KeyError: "labels ['Score'] not contained in axis"

In [73]:
Data_Frame.drop('A',axis=1,inplace=True)

KeyError: "labels ['A'] not contained in axis"

In [74]:
Data_Frame.drop('A',axis=0,inplace=True)

In [75]:
Data_Frame

Score1    Score2    Score3
B  0.255001 -0.458027  0.435163

In [76]:
Data_Frame.loc['B']

Score1    0.255001
Score2   -0.458027
Score3    0.435163
Name: B, dtype: float64

In [77]:
Data_Frame.iloc['0']

TypeError: cannot do positional indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [0] of <class 'str'>

In [78]:
Data_Frame.iloc[1]

IndexError: single positional indexer is out-of-bounds

In [79]:
Data_Frame.iloc[0]

Score1    0.255001
Score2   -0.458027
Score3    0.435163
Name: B, dtype: float64

In [80]:
Data_Frame.loc['B','Score3']

0.43516348812289213

In [81]:
Data_Frame

Score1    Score2    Score3
B  0.255001 -0.458027  0.435163

In [84]:
Data_Frame[Data_Frame['Score3']>0.1]['Score1' 'Score3']

KeyError: 'Score1Score3'

In [85]:
Data_Frame[Data_Frame['Score3']>0.1][['Score1' 'Score3']]

KeyError: "['Score1Score3'] not in index"

In [86]:
Data_Frame[Data_Frame['Score3']>0.1][['Score1' 'Score2']]Data_Frame[Data_Frame['Score3']>0.1][['Score1' 'Score2']]

KeyError: "['Score1Score2'] not in index"

In [87]:
Data_Frame[Data_Frame['Score3']>0.1][['Score1','Score2']]

Score1    Score2
B  0.255001 -0.458027

In [89]:
Data_Frame=pd.DataFrame(randn(5,3),index='A B'.split(),columns='Score1 Score2 Score3'.split())

ValueError: Shape of passed values is (3, 5), indices imply (3, 2)

In [91]:
Data_Frame=pd.DataFrame(randn(5,3),index='A,B,C,D,E'.split(','),columns='Score1 Score2 Score3'.split())

In [93]:
Data_Frame.reset_index()

index    Score1    Score2    Score3
0     A -1.613579  1.470714 -1.188018
1     B -0.549746 -0.940046 -0.827932
2     C  0.108863  0.507810 -0.862227
3     D  1.249470 -0.079611 -0.889731
4     E -0.881798  0.018639  0.237845

In [94]:
Data_Frame

Score1    Score2    Score3
A -1.613579  1.470714 -1.188018
B -0.549746 -0.940046 -0.827932
C  0.108863  0.507810 -0.862227
D  1.249470 -0.079611 -0.889731
E -0.881798  0.018639  0.237845

In [111]:
New_index='X' 'Y' 'Z' 'Q' 'W'.split()

In [112]:
New_index

['XYZQW']

In [113]:
Data_Frame['cou']=New_index



ValueError: Length of values does not match length of index

In [114]:
Data_Frame

Score1    Score2    Score3
A -1.613579  1.470714 -1.188018
B -0.549746 -0.940046 -0.827932
C  0.108863  0.507810 -0.862227
D  1.249470 -0.079611 -0.889731
E -0.881798  0.018639  0.237845

In [115]:
Data_Frame['cou']=New_index

ValueError: Length of values does not match length of index

In [107]:
New_index

['XYZQW']

In [119]:
dataframe = pd.DataFrame({'Cricket':[1,2,np.nan,4,6,7,2,np.nan,np.nan],
                  'Baseball':[5,np.nan,np.nan,5,7,2,4,5,np.nan],
                  'Tennis':[1,2,3,4,5,6,7,8,9]})

In [120]:
dataframe

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      2.0       NaN       2
2      NaN       NaN       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       2.0       6
6      2.0       4.0       7
7      NaN       5.0       8
8      NaN       NaN       9

In [121]:
dataframe.dropna(axis=1)

Tennis
0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8
8       9

In [122]:
dataframe.dropna(axis=0)

Cricket  Baseball  Tennis
0      1.0       5.0       1
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       2.0       6
6      2.0       4.0       7

In [124]:
dataframe.dropna(thresh=1)

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      2.0       NaN       2
2      NaN       NaN       3
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       2.0       6
6      2.0       4.0       7
7      NaN       5.0       8
8      NaN       NaN       9

In [125]:
dataframe.dropna(thresh=2)

Cricket  Baseball  Tennis
0      1.0       5.0       1
1      2.0       NaN       2
3      4.0       5.0       4
4      6.0       7.0       5
5      7.0       2.0       6
6      2.0       4.0       7
7      NaN       5.0       8

In [126]:
dataframe['Cricket'].fillna(value=dataframe['Cricket'].mean())

0    1.000000
1    2.000000
2    3.666667
3    4.000000
4    6.000000
5    7.000000
6    2.000000
7    3.666667
8    3.666667
Name: Cricket, dtype: float64

In [127]:
dataframe.describe()

Cricket  Baseball    Tennis
count  6.000000  6.000000  9.000000
mean   3.666667  4.666667  5.000000
std    2.422120  1.632993  2.738613
min    1.000000  2.000000  1.000000
25%    2.000000  4.250000  3.000000
50%    3.000000  5.000000  5.000000
75%    5.500000  5.000000  7.000000
max    7.000000  7.000000  9.000000

In [128]:
dataframe.describe().transpose()

count      mean       std  min   25%  50%  75%  max
Cricket     6.0  3.666667  2.422120  1.0  2.00  3.0  5.5  7.0
Baseball    6.0  4.666667  1.632993  2.0  4.25  5.0  5.0  7.0
Tennis      9.0  5.000000  2.738613  1.0  3.00  5.0  7.0  9.0

In [129]:
dataframe['Baseball'].describe()

count    6.000000
mean     4.666667
std      1.632993
min      2.000000
25%      4.250000
50%      5.000000
75%      5.000000
max      7.000000
Name: Baseball, dtype: float64

In [130]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
Cricket     6 non-null float64
Baseball    6 non-null float64
Tennis      9 non-null int64
dtypes: float64(2), int64(1)
memory usage: 296.0 bytes


In [131]:
data_frame2=pd.read_csv('pandas-train.csv')

In [133]:
data_frame2.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [134]:
data_frame2.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [138]:
data_frame2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [140]:
data_frame2.to_csv('tet.csv',index=False)